version: '2.1'

services:
  cypress:
    image: cypress/included:6.4.0
    container_name: cypress_e2e
    working_dir: /e2e
    volumes:
      - ./voting_app_cypress/cypress.json:/e2e/cypress.json
      - ./voting_app_cypress/cypress:/e2e/cypress